# Generated by Django 4.0.3 on 2022-04-23 22:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=25, verbose_name='Apellido')),
                ('birth_date', models.DateField(help_text='Usa el siguiente formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha de nacimiento')),
                ('phone', models.IntegerField(verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('address', models.CharField(help_text='Usa el siguiente formato: <em>Calle,número,Población,Comuna</em>.', max_length=100, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='labtienda.user')),
                ('ci', models.CharField(help_text='Usa el siguiente formato: <em>xxxxxxxx-x o xxxxxxxx-x</em>.', max_length=10, unique=True, verbose_name='Run o Rut')),
            ],
            bases=('labtienda.user',),
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='labtienda.user')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('ci', models.CharField(max_length=9, unique=True, verbose_name='Run')),
                ('registration_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de registro')),
            ],
            bases=('labtienda.user',),
        ),
    ]
