# Generated by Django 4.0.3 on 2022-05-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='ci',
            field=models.CharField(max_length=10, unique=True, verbose_name='Run'),
        ),
    ]
