# Generated by Django 4.0.3 on 2022-05-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtienda', '0002_alter_professional_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('correo_electronico', models.EmailField(max_length=30)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
