# Generated by Django 4.0.3 on 2022-05-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labtienda', '0004_categoria_marca_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='image',
            new_name='imagen',
        ),
    ]
