# Generated by Django 4.0.3 on 2022-05-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labtienda', '0005_rename_image_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
