# Generated by Django 4.0.3 on 2022-05-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtienda', '0007_orden_ordenitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='usuario',
        ),
        migrations.AddField(
            model_name='orden',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
